# ENGR 418 Project - Stage 1
## Sorting using raw images

- Group #20
- Jesse Adele 
- Zach Kelly 41637836

Import python modules

In [1]:
import numpy as np 
import matplotlib.pyplot as plt
import os
from numpy import asarray
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score
from PIL import Image

Define function to get training and testing data from raw image files

In [52]:
im_width = int(np.sqrt(4067))
im_length = int(np.sqrt(4067))

def get_data(folder, im_width, im_length):

    # create list of file names inside folder
    file_names = os.listdir(folder)
    # intialize np array to store feature data
    x = np.empty((len(file_names),im_width*im_length))
    # initialize np array to store class labels
    y = np.empty((len(file_names),1))
    
    num_cir = 0 # Number of images that are labelled as circle
    num_rec = 0 # Number of images that are labelled as rectangle
    num_squ = 0 # Number of images that are labelled as square
    
    for i in range(len(file_names)):
       
        # fill class labels array
        if 'cir' in file_names[i]:
            y[i] = 0 # class circle
            #num_cir = num_cir + 1
        elif 'rec' in file_names[i]:
            y[i] = 1 # class rectangle
            #num_rec = num_rec + 1
        elif 'squ' in file_names[i]:
            y[i] = 2 # class square
            #num_squ = num_squ + 1
        # fill feature array
        
        path = folder + '/' + file_names[i]
        im = Image.open(path).convert('L')
        im = im.resize((im_length,im_width))
        im_array = asarray(im) 
        x[i,:] = im_array.reshape(1,-1)

    return x, y

Training analysis

In [69]:
# Define training folder path
training_folder = r"C:\Users\zachk\Documents\ubco\year5\ubc_term1\engr418\project\Lego_dataset_1\training"

x_train, y_train = get_data(training_folder,im_width,im_length)

model = LogisticRegression()
model.fit(x_train, y_train)

y_train_pred = model.predict(x_train)

print(f'The confusion matrix is:\n {confusion_matrix(y_train,y_train_pred)}')
print(f'The accuracy score on the circles is: {accuracy_score(y_train[0:int(len(y_train)/3),0],y_train_pred[0:int(len(y_train_pred)/3)])*100:.2f}%')
print(f'The accuracy score on the rectangles is: {accuracy_score(y_train[int(len(y_train)/3):int((2*len(y_train))/3),0],y_train_pred[int(len(y_train_pred)/3):int((2*len(y_train_pred))/3)])*100:.2f}%')
print(f'The accuracy score on the squares is: {accuracy_score(y_train[int((2*len(y_train))/3):int(len(y_train)),0],y_train_pred[int((2*len(y_train_pred))/3):int(len(y_train_pred))])*100:.2f}%')
print(f'The accuracy score on the training data set is: {accuracy_score(y_train,y_train_pred)*100:.2f}%')

c:\Users\zachk\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


The confusion matrix is:
 [[36  0  0]
 [ 0 36  0]
 [ 0  0 36]]
The accuracy score on the circles is: 100.00%
The accuracy score on the rectangles is: 100.00%
The accuracy score on the squares is: 100.00%
The accuracy score on the training data set is: 100.00%


c:\Users\zachk\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Testing analysis

In [67]:
# Define training folder path
testing_folder = r"C:\Users\zachk\Documents\ubco\year5\ubc_term1\engr418\project\Lego_dataset_1\testing"

x_test, y_test = get_data(testing_folder,im_width,im_length) # store the returned data from get_data as x_test, y_test

y_test_pred = model.predict(x_test)

print(f'The confusion matrix is:\n {confusion_matrix(y_test,y_test_pred)}')
print(list(y_test),list(y_test_pred))
print(len(y_test)/3)
print(f'The accuracy score on the circles is: {accuracy_score(y_test[0:int(len(y_test)/3),0],y_test_pred[0:int(len(y_test)/3)])*100:.2f}%')
print(f'The accuracy score on the rectangles is: {accuracy_score(y_test[int(len(y_test)/3):int((2*len(y_test))/3),0],y_test_pred[int(len(y_test)/3):int((2*len(y_test))/3)])*100:.2f}%')
print(f'The accuracy score on the squares is: {accuracy_score(y_test[int((2*len(y_test))/3):int(len(y_test)),0],y_test_pred[int((2*len(y_test))/3):int(len(y_test))])*100:.2f}%')
print(f'The accuracy score on the entire training dataset is: {accuracy_score(y_test,y_test_pred)*100:.2f}%')

[array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([0.]), array([1.]), array([1.]), array([1.]), array([1.]), array([1.]), array([1.]), array([1.]), array([1.]), array([1.]), array([1.]), array([1.]), array([1.]), array([1.]), array([1.]), array([1.]), array([1.]), array([1.]), array([1.]), array([2.]), array([2.]), array([2.]), array([2.]), array([2.]), array([2.]), array([2.]), array([2.]), array([2.]), array([2.]), array([2.]), array([2.]), array([2.]), array([2.]), array([2.]), array([2.]), array([2.]), array([2.])] [0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 0.0, 2.0]
18.0
The accuracy score on