# ENGR 418 Project - Stage 1
## Sorting using raw images

- Group #20
- Jesse Alele 82807728
- Zach Kelly 41637836

Import python modules

In [7]:
import numpy as np 
import matplotlib.pyplot as plt
import os
from numpy import asarray
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score
from PIL import Image

Define function to get training and testing data from raw image files

In [8]:
im_width = int(np.sqrt(4067)) 
im_length = int(np.sqrt(4067))

def get_data(folder, im_width, im_length):

    # create list of file names inside folder
    file_names = os.listdir(folder)
    # intialize np array to store feature data
    x = np.empty((len(file_names),im_width*im_length))
    # initialize np array to store class labels
    y = np.empty((len(file_names),1))
    
    num_cir = 0 # number of images that are labelled as class circle
    num_rec = 0 # number of images that are labelled as class rectangle
    num_squ = 0 # number of images that are labelled as class square
    
    for i in range(len(file_names)):
       
        # fill class labels array
        if 'cir' in file_names[i]:
            y[i] = 0 # class circle
            num_cir = num_cir + 1 # keep running count of circle labels
        elif 'rec' in file_names[i]:
            y[i] = 1 # class rectangle
            num_rec = num_rec + 1 # keep running count of rectangle labels
        elif 'squ' in file_names[i]:
            y[i] = 2 # class square
            num_squ = num_squ + 1 # keep running count of square labels
            
        # fill feature array
        path = folder + '/' + file_names[i] # update path as we iterate through file_names array
        im = Image.open(path).convert('L') # open ith image and convert to grayscale
        im = im.resize((im_length,im_width)) # resize to specified pixel length and width
        im_array = asarray(im) # convert to numpy array
        x[i,:] = im_array.reshape(1,-1) # reshape to im_length*im_width columns by one row then insert as ith row in x
    
    # assure the folder contains an equal count of each different shape, so only one variable (num_shape) is needed to seperate the shapes in class labels array
    if num_cir == num_rec == num_squ:
        num_shape = num_cir
    else:
        print('The number of circles, rectangles and squares in the specified folder are not equal')

    return x, y, num_shape

Training analysis

In [9]:
# Define training folder path
training_folder = r"C:\Users\zachk\Documents\ubco\year5\ubc_term1\engr418\project\Lego_dataset_1\training"
# store the returned data from get_data as x_train, y_train, num_shape
x_train, y_train, num_shape = get_data(training_folder,im_width,im_length) 

model = LogisticRegression() 
model.fit(x_train, y_train)

y_train_pred = model.predict(x_train)

print(f'The confusion matrix is:\n {confusion_matrix(y_train,y_train_pred)}')
print(f'The accuracy score on the circles is: {accuracy_score(y_train[0:num_shape,0],y_train_pred[0:num_shape])*100:.2f}%')
print(f'The accuracy score on the rectangles is: {accuracy_score(y_train[num_shape:2*num_shape,0],y_train_pred[num_shape:2*num_shape])*100:.2f}%')
print(f'The accuracy score on the squares is: {accuracy_score(y_train[2*num_shape:3*num_shape,0],y_train_pred[2*num_shape:3*num_shape])*100:.2f}%')
print(f'The accuracy score on the training data set is: {accuracy_score(y_train,y_train_pred)*100:.2f}%')

c:\Users\zachk\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


The confusion matrix is:
 [[36  0  0]
 [ 0 36  0]
 [ 0  0 36]]
The accuracy score on the circles is: 100.00%
The accuracy score on the rectangles is: 100.00%
The accuracy score on the squares is: 100.00%
The accuracy score on the training data set is: 100.00%


c:\Users\zachk\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Testing analysis

In [10]:
# define testing folder path
testing_folder = r"C:\Users\zachk\Documents\ubco\year5\ubc_term1\engr418\project\Lego_dataset_1\testing"
# store the returned data from get_data as x_test, y_test, num_shape
x_test, y_test, num_shape = get_data(testing_folder,im_width,im_length) 

def test_function(folder, im_width, im_length):

    # create list of file names inside folder
    file_names = os.listdir(folder)
    # intialize np array to store feature data
    x = np.empty((len(file_names),im_width*im_length))
    # initialize np array to store class labels
    y = np.empty((len(file_names),1))
    
    num_cir = 0 # number of images that are labelled as class circle
    num_rec = 0 # number of images that are labelled as class rectangle
    num_squ = 0 # number of images that are labelled as class square
    
    for i in range(len(file_names)):
       
        # fill class labels array
        if 'cir' in file_names[i]:
            y[i] = 0 # class circle
            num_cir = num_cir + 1 # keep running count of cirlce labels
        elif 'rec' in file_names[i]: 
            y[i] = 1 # class rectangle
            num_rec = num_rec + 1 # keep running count of rectangle labels
        elif 'squ' in file_names[i]: 
            y[i] = 2 # class square
            num_squ = num_squ + 1 # keep running count of square labels
            
        # fill feature array
        path = folder + '/' + file_names[i] # update path as we iterate through file_names array
        im = Image.open(path).convert('L') # open ith image and convert to grayscale
        im = im.resize((im_length,im_width)) # resize to specified pixel length and width
        im_array = asarray(im) # convert to numpy array
        x[i,:] = im_array.reshape(1,-1) # reshape to im_length*im_width columns by one row then insert as ith row in x
    
    # assure the folder contains an equal number of the different shapes, so only one variable (num_shape) is needed to seperate the shapes in class labels array
    if num_cir == num_rec == num_squ:
        num_shape = num_cir
    else: 
        print('The number of circles, rectangles and squares in the specified folder are not equal')

    y_test_pred = model.predict(x)
    test_accuracy = accuracy_score(y,y_test_pred)
    cir_accuracy = accuracy_score(y_test[0:num_shape,0],y_test_pred[0:num_shape])
    rec_accuracy = accuracy_score(y_test[num_shape:2*num_shape,0],y_test_pred[num_shape:2*num_shape])
    squ_accuracy = accuracy_score(y_test[2*num_shape:3*num_shape,0],y_test_pred[2*num_shape:3*num_shape])
    test_confusion = confusion_matrix(y,y_test_pred)
    
    return test_confusion, test_accuracy, cir_accuracy, rec_accuracy, squ_accuracy

test_confusion, test_accuracy, cir_accuracy, rec_accuracy, squ_accuracy = test_function(testing_folder,im_width,im_length)


print(f'The confusion matrix is:\n {test_confusion}')
print(f'The accuracy score on the circles is: {cir_accuracy*100:.2f}%')
print(f'The accuracy score on the rectangles is: {rec_accuracy*100:.2f}%')
print(f'The accuracy score on the squares is: {squ_accuracy*100:.2f}%')
print(f'The accuracy score on the entire training dataset is: {test_accuracy*100:.2f}%')


The confusion matrix is:
 [[17  0  1]
 [ 0 17  1]
 [ 1  0 17]]
The accuracy score on the circles is: 94.44%
The accuracy score on the rectangles is: 94.44%
The accuracy score on the squares is: 94.44%
The accuracy score on the entire training dataset is: 94.44%


In [16]:
im_width_test = [20, 25, 50, 63]
im_length_test = [20, 25, 50, 63]
test_confusions = []
test_accuracies = []

for i in range(4):

    im_width = im_width_test[i]
    im_length = im_length_test[i]

    test_confusion, test_accuracy, cir_accuracy, rec_accuracy, squ_accuracy = test_function(testing_folder, im_width, im_length)

    test_confusions[i] = test_confusion
    test_accuracies[i] = test_accuracy

ValueError: X has 100 features, but LogisticRegression is expecting 3969 features as input.